from enum import Enum


class ToolSpecTypeType0(str, Enum):
    ARCHIVE_AGENT = "archive_agent"
    ARCHIVE_RUN = "archive_run"
    ARCHIVE_WORKFLOW = "archive_workflow"
    BASH = "bash"
    CALL_AGENT = "call_agent"
    CALL_SESSION = "call_session"
    CALL_WORKFLOW = "call_workflow"
    CREATE_AGENT = "create_agent"
    CREATE_GOAL = "create_goal"
    CREATE_WORKFLOW = "create_workflow"
    CTX_EVAL = "ctx_eval"
    CTX_GREP = "ctx_grep"
    CTX_LIST = "ctx_list"
    CTX_PEEK = "ctx_peek"
    CTX_WRITE = "ctx_write"
    DEFER_OBLIGATIONS = "defer_obligations"
    EDIT = "edit"
    GET_AGENT = "get_agent"
    GET_RUN = "get_run"
    GET_WORKFLOW = "get_workflow"
    GLOB = "glob"
    GREP = "grep"
    HTTP_REQUEST = "http_request"
    LIST_ACCOUNT_TRIGGERS = "list_account_triggers"
    LIST_AGENTS = "list_agents"
    LIST_OBLIGATIONS = "list_obligations"
    LIST_RELATED_SESSIONS = "list_related_sessions"
    LIST_RUNS = "list_runs"
    LIST_RUN_EVENTS = "list_run_events"
    LIST_TASKS = "list_tasks"
    LIST_WORKFLOWS = "list_workflows"
    MEMORY_SEARCH = "memory_search"
    READ = "read"
    RESUME_GATE = "resume_gate"
    RLM_MAP = "rlm_map"
    RLM_QUERY = "rlm_query"
    RLM_VERIFY = "rlm_verify"
    SCHEDULE_WAKE = "schedule_wake"
    SEARCH_EVENTS = "search_events"
    SKILL_ARCHIVE = "skill_archive"
    SKILL_UPSERT = "skill_upsert"
    STOP_TASK = "stop_task"
    TRIGGER_CREATE = "trigger_create"
    TRIGGER_LIST = "trigger_list"
    TRIGGER_REMOVE = "trigger_remove"
    TRIGGER_UPDATE = "trigger_update"
    UNARCHIVE_WORKFLOW = "unarchive_workflow"
    UPDATE_AGENT = "update_agent"
    UPDATE_WORKFLOW = "update_workflow"
    WAKE_SELF = "wake_self"
    WAKE_SESSION = "wake_session"
    WEB_FETCH = "web_fetch"
    WEB_SEARCH = "web_search"
    WRITE = "write"

    def __str__(self) -> str:
        return str(self.value)
